# Generated by Django 5.2.3 on 2025-07-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarexUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('college', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
